services:
  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: jenkins-iac
    ports:
      - "8012:8080"
      - "50012:50000"
    volumes:
      - ./docker/jenkins:/var/jenkins_home/data
    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    ports:
      - "8212:8200"
    cap_add:
      - IPC_LOCK
